LSF_DICO_VIDEO_BASE = "https://lsfdico.injs-metz.fr/wp-content/uploads/videos"
ELIX_VIDEO_BASE = "https://elix-lsf.s3.rbx.io.cloud.ovh.net/spip_videos"

WORDS = [
    {"id": "bonjour", "label": "Bonjour", "video_url": f"{LSF_DICO_VIDEO_BASE}/bonjour.mp4"},
    {"id": "salut", "label": "Salut", "video_url": f"{LSF_DICO_VIDEO_BASE}/salut.mp4"},
    {"id": "au-revoir", "label": "Au revoir", "video_url": f"{LSF_DICO_VIDEO_BASE}/au_revoir.mp4"},
    {"id": "merci", "label": "Merci", "video_url": f"{LSF_DICO_VIDEO_BASE}/merci.mp4"},
    {"id": "s-il-te-plait", "label": "S'il te plaît", "video_url": f"{ELIX_VIDEO_BASE}/02252.mp4"},
    {"id": "pardon", "label": "Pardon", "video_url": f"{LSF_DICO_VIDEO_BASE}/pardon.mp4"},
    {"id": "oui", "label": "Oui", "video_url": f"{ELIX_VIDEO_BASE}/oui_adv_1_1.mp4"},
    {"id": "non", "label": "Non", "video_url": f"{ELIX_VIDEO_BASE}/non_adv_1_1.mp4"},
    {"id": "encore", "label": "Encore", "video_url": f"{ELIX_VIDEO_BASE}/encore_adv_2_1.mp4"},
    {"id": "comprendre", "label": "Comprendre", "video_url": f"{ELIX_VIDEO_BASE}/comprendre_v_4_6.mp4"},
    {"id": "repeter", "label": "Répéter", "video_url": f"{ELIX_VIDEO_BASE}/00161-2.mp4"},
    {"id": "lentement", "label": "Lentement", "video_url": f"{ELIX_VIDEO_BASE}/lentement_adv_1_1.mp4"},
    {"id": "signer", "label": "Signer", "video_url": f"{ELIX_VIDEO_BASE}/signer_v_10_6.mp4"},
    {"id": "parler", "label": "Parler", "video_url": f"{ELIX_VIDEO_BASE}/parler_nm_2_1_6.mp4"},

    {"id": "moi", "label": "Moi", "video_url": f"{LSF_DICO_VIDEO_BASE}/moi.mp4"},
    {"id": "toi", "label": "Toi", "video_url": f"{LSF_DICO_VIDEO_BASE}/toi.mp4"},
    {"id": "lui-elle", "label": "Lui/Elle", "video_url": f"{ELIX_VIDEO_BASE}/elle_pro_1_1_6.mp4"},
    {"id": "nous", "label": "Nous", "video_url": f"{LSF_DICO_VIDEO_BASE}/nous.mp4"},
    {"id": "vous", "label": "Vous", "video_url": f"{LSF_DICO_VIDEO_BASE}/vous.mp4"},
    {"id": "nom", "label": "Nom", "video_url": f"{LSF_DICO_VIDEO_BASE}/nom.mp4"},
    {"id": "prenom", "label": "Prénom", "video_url": f"{LSF_DICO_VIDEO_BASE}/prenom.mp4"},
    {"id": "age", "label": "Âge", "video_url": f"{LSF_DICO_VIDEO_BASE}/age.mp4"},
    {"id": "personne", "label": "Personne", "video_url": f"{ELIX_VIDEO_BASE}/personne_nf_1_1.mp4"},
    {"id": "homme", "label": "Homme", "video_url": f"{LSF_DICO_VIDEO_BASE}/homme.mp4"},
    {"id": "femme", "label": "Femme", "video_url": f"{LSF_DICO_VIDEO_BASE}/femme.mp4"},
    {"id": "enfant", "label": "Enfant", "video_url": f"{ELIX_VIDEO_BASE}/&.mp4"},
    {"id": "etre", "label": "Être", "video_url": f"{ELIX_VIDEO_BASE}/etre_nm_1_1.mp4"},
    {"id": "s-appeler", "label": "S'appeler", "video_url": f"{ELIX_VIDEO_BASE}/00344-4.mp4"},
    {"id": "habiter", "label": "Habiter", "video_url": f"{LSF_DICO_VIDEO_BASE}/habiter.mp4"},
    {"id": "venir", "label": "Venir", "video_url": f"{ELIX_VIDEO_BASE}/venir_v_1_1.mp4"},

    {"id": "france", "label": "France", "video_url": f"{LSF_DICO_VIDEO_BASE}/france.mp4"},
    {"id": "ville", "label": "Ville", "video_url": f"{LSF_DICO_VIDEO_BASE}/ville.mp4"},
    {"id": "pays", "label": "Pays", "video_url": f"{LSF_DICO_VIDEO_BASE}/pays.mp4"},
    {"id": "ici", "label": "Ici", "video_url": f"{ELIX_VIDEO_BASE}/ici.mp4"},
    {"id": "la-bas", "label": "Là-bas", "video_url": f"{ELIX_VIDEO_BASE}/la-bas_adv_1_1.mp4"},
    {"id": "ou", "label": "Où", "video_url": f"{ELIX_VIDEO_BASE}/ou_adv_1_1.mp4"},
    {"id": "chez", "label": "Chez", "video_url": f"{ELIX_VIDEO_BASE}/chez_prp_1_1.mp4"},
    {"id": "maison", "label": "Maison", "video_url": f"{ELIX_VIDEO_BASE}/maison_adj_1_6.mp4"},
    {"id": "appartement", "label": "Appartement", "video_url": f"{LSF_DICO_VIDEO_BASE}/appartement.mp4"},
    {"id": "vivre", "label": "Vivre", "video_url": f"{ELIX_VIDEO_BASE}/vivre_nm_2_6.mp4"},
    {"id": "partir", "label": "Partir", "video_url": f"{ELIX_VIDEO_BASE}/partir_v_3_1.mp4"},
    {"id": "arriver", "label": "Arriver", "video_url": f"{ELIX_VIDEO_BASE}/arriver_v_1_1.mp4"},
    {"id": "paris", "label": "Paris", "video_url": f"{ELIX_VIDEO_BASE}/paris.mp4"},


    {"id": "bonsoir", "label": "Bonsoir", "video_url": f"{LSF_DICO_VIDEO_BASE}/bonsoir.mp4"},
    {"id": "bonne-nuit", "label": "Bonne nuit", "video_url": f"{LSF_DICO_VIDEO_BASE}/bonne_nuit.mp4"},
    {"id": "bienvenue", "label": "Bienvenue", "video_url": f"{LSF_DICO_VIDEO_BASE}/bienvenue.mp4"},
    {"id": "excuse-moi", "label": "Excuse-moi", "video_url": f"{LSF_DICO_VIDEO_BASE}/excuse-moi.mp4"},
    {"id": "ca-va", "label": "Ça va", "video_url": f"{LSF_DICO_VIDEO_BASE}/ca_va.mp4"},
    {"id": "bien", "label": "Bien", "video_url": f"{LSF_DICO_VIDEO_BASE}/bien.mp4"},
    {"id": "mal", "label": "Mal", "video_url": f"{LSF_DICO_VIDEO_BASE}/mal.mp4"},
    {"id": "content", "label": "Content", "video_url": f"{LSF_DICO_VIDEO_BASE}/content.mp4"},
    {"id": "fatigue", "label": "Fatigué", "video_url": f"{LSF_DICO_VIDEO_BASE}/fatigue.mp4"},
    {"id": "je", "label": "Je", "video_url": f"{LSF_DICO_VIDEO_BASE}/je.mp4"},
    {"id": "mon", "label": "Mon", "video_url": f"{LSF_DICO_VIDEO_BASE}/mon.mp4"},
    {"id": "appeler", "label": "Appeler", "video_url": f"{LSF_DICO_VIDEO_BASE}/appeler.mp4"},
    {"id": "presenter", "label": "Présenter", "video_url": f"{LSF_DICO_VIDEO_BASE}/presenter.mp4"},
    {"id": "date", "label": "Date", "video_url": f"{LSF_DICO_VIDEO_BASE}/date.mp4"},
    {"id": "naissance", "label": "Naissance", "video_url": f"{LSF_DICO_VIDEO_BASE}/naissance.mp4"},
    {"id": "sourd", "label": "Sourd", "video_url": f"{LSF_DICO_VIDEO_BASE}/sourd.mp4"},
    {"id": "entendant", "label": "Entendant", "video_url": f"{LSF_DICO_VIDEO_BASE}/entendant.mp4"},
    {"id": "lsf", "label": "LSF", "video_url": f"{LSF_DICO_VIDEO_BASE}/lsf.mp4"},
    {"id": "francais", "label": "Français", "video_url": f"{LSF_DICO_VIDEO_BASE}/francais.mp4"},
    {"id": "adresse", "label": "Adresse", "video_url": f"{LSF_DICO_VIDEO_BASE}/adresse.mp4"},
    {"id": "telephone", "label": "Téléphone", "video_url": f"{LSF_DICO_VIDEO_BASE}/telephone.mp4"},
    {"id": "famille", "label": "Famille", "video_url": f"{LSF_DICO_VIDEO_BASE}/famille.mp4"},
    {"id": "ami", "label": "Ami", "video_url": f"{LSF_DICO_VIDEO_BASE}/ami.mp4"},
    {"id": "travailler", "label": "Travailler", "video_url": f"{LSF_DICO_VIDEO_BASE}/travailler.mp4"},
    {"id": "metier", "label": "Métier", "video_url": f"{LSF_DICO_VIDEO_BASE}/metier.mp4"},
    {"id": "etudiant", "label": "Étudiant", "video_url": f"{LSF_DICO_VIDEO_BASE}/etudiant.mp4"},
    {"id": "ecole", "label": "École", "video_url": f"{LSF_DICO_VIDEO_BASE}/ecole.mp4"},
    {"id": "un", "label": "Un", "video_url": f"{LSF_DICO_VIDEO_BASE}/un.mp4"},
    {"id": "deux", "label": "Deux", "video_url": f"{LSF_DICO_VIDEO_BASE}/deux.mp4"},
    {"id": "trois", "label": "Trois", "video_url": f"{LSF_DICO_VIDEO_BASE}/trois.mp4"},
    {"id": "quatre", "label": "Quatre", "video_url": f"{LSF_DICO_VIDEO_BASE}/quatre.mp4"},
    {"id": "cinq", "label": "Cinq", "video_url": f"{LSF_DICO_VIDEO_BASE}/cinq.mp4"},
    {"id": "six", "label": "Six", "video_url": f"{LSF_DICO_VIDEO_BASE}/six.mp4"},
    {"id": "sept", "label": "Sept", "video_url": f"{LSF_DICO_VIDEO_BASE}/sept.mp4"},
    {"id": "huit", "label": "Huit", "video_url": f"{LSF_DICO_VIDEO_BASE}/huit.mp4"},
    {"id": "neuf", "label": "Neuf", "video_url": f"{LSF_DICO_VIDEO_BASE}/neuf.mp4"},
    {"id": "dix", "label": "Dix", "video_url": f"{LSF_DICO_VIDEO_BASE}/dix.mp4"},
]

WORDS_BY_ID = {w["id"]: w for w in WORDS}
